version: 2.1
jobs:
  build:
    docker:
      - image: dockerfile
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t your-image-name:tag -f node-test/Dockerfile .
