version: 2.1
jobs:
  build:
    context: dockerhub
    docker:
      - image: dockerfile
        auth:
          username: $user
          password: $pass
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t node-test -f node-test/Dockerfile .
