version: 2.1

jobs:
  build-node-image:
    docker:
      - image: cimg/node
    steps:
      - checkout  
      - setup_remote_docker  
      - run:
          name: Build Docker image
          command: 
            docker build -t node-test -f node-test/Dockerfile .
            docker image ls
          
  trivy-scan:
    docker:
      - image: aquasec/trivy
    steps:
      - run:
          name: run trivy
          command: 
            usermod -aG docker $user
            trivy image node-test

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build-node-image
      - trivy-scan
