version: 2.1

jobs:
  build-node-image:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout  
      - setup_remote_docker  
      - run:
          name: Build Docker image
          command: 
            sudo apt-get update
            pwd
            ls

 workflows:
   version: 2
   build-and-scan:
     jobs:
       - build-node-image

