version: 2.1

jobs:
  build_node:
    docker:
      - image: node:latest  

    steps:
      - checkout

      - run:
          name: Install Node.js dependencies
          command: |
            cd node-test
            npm install

workflows:
  version: 2
  build:
    jobs:
      - build_node
