version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: 
            - dockerhub

jobs:
  build:
    docker:
      - image: dockerfile
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          command:
            echo $user
            docker build -t node-test -f node-test/Dockerfile .
