version: 2.1
orbs:
  trivy-orb: fifteen5/trivy-orb@1.0.0

jobs:
  build_node:
    docker:
      - image: node:latest  

    steps:
      - checkout

      - run:
          name: Install Node.js dependencies
          command: |
            cd node-test
            npm install

workflows:
  version: 2
  build:
    jobs:
      - build_node
      - trivy/scan
