version: 2.1

jobs:
  build-node-image:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout  
      - setup_remote_docker  
      - run:
          name: Build Docker image
          command: |
            docker build -t node-test -f node-test/Dockerfile .
            docker image ls
            docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.48.2 image node-test

 
workflows:
  version: 2
  build-and-scan:
    jobs:
      - build-node-image