version: 2.1

jobs:
  build-node-image:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout  
      - setup_remote_docker  
      - run:
          name: Build Docker image
          command: |
            docker build -t node-test -f node-test/Dockerfile .
            docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy  image node-test 
      - run:
          name: security team check
          when: on_fail
          command: |
            echo 'you need wait for security check'

  test-run:
    docker:
      - image: cimg/base:2024.01
    steps:
      - run:
          name: testetsetsetset
          command: |
            echo 'aaaaaaaaaaaaaaaaa'
          
workflows:
  version: 2
  build-and-scan:
    jobs:
      - build-node-image
      - hold:
          type: approval
          requires:
            - build-node-image
      - test-run:
          requires:
            - hold
      

