version: 2.1

jobs:
  build_node:
    docker:
      - image: node:latest  

    steps:
      - checkout

      - run:
          name: Install Node.js dependencies
          command: |
            cd /app
            npm install


  build_go:
    docker:
      - image: golang:latest 

    steps:
      - checkout
      - run:
          name: Run Go tests
          command: |
            cd /app

workflows:
  version: 2
  build:
    jobs:
      - build_node
      - build_go
